name: Simple Promote to GitLab

on:
  push:
    branches: [main]

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@bot.com"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/jedidimanef-group/testing-gitlab-pormote.git

          # Debug (optional)
          git remote -v

          # Push
          git push gitlab main --force
