name: Promote to GitLab

on:
  push:
    branches: [main]

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "thegr8manef"
          git config user.email "jedidimanef@gmail.com"

      - name: Push to GitLab
        run: |
          git remote remove gitlab || true

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/jedidimanef-group/testing-gitlab-pormote.git

          # 🔥 This will FAIL if token is wrong (good for debug)
          git ls-remote gitlab

          # Push mirror
          git push gitlab main --force
